---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: backstage
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: backstage
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: backstage-read-only
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - configmaps
      - services
      - limitranges
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - 'apps'
    verbs:
      - get
      - list
      - watch
    resources:
      - statefulsets
      - deployments
      - daemonsets
      - replicasets
  - apiGroups:
      - 'autoscaling'
    verbs:
      - get
      - list
      - watch
    resources:
      - horizontalpodautoscalers

  - apiGroups:
      - 'networking.k8s.io'
    verbs:
      - get
      - list
      - watch
    resources:
      - ingresses
  - apiGroups:
      - metrics.k8s.io
    verbs:
      - get
      - list
      - watch
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: backstage-binding
subjects:
  - kind: ServiceAccount
    name: backstage
    namespace: default
roleRef:
  kind: ClusterRole
  name: backstage-read-only
  apiGroup: rbac.authorization.k8s.io

