apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    github.com/project-slug: ${{ values.repoOwner }}/${{ values.repoName }}
  tags:
    - web
    - nginx
spec:
  type: service
  owner: user:guest
  lifecycle: experimental

