apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: nextjs-template
  title: nextjs Template
  description: An template for a simple nextjs project
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./nextjs
        values:
          name: ${{ parameters.name }}

    - id: fetch-actions
      name: Fetch Github Action
      action: fetch:template
      input:
        # gh action uses the same syntax for templating, so we ignore all templating
        copyWithoutTemplating:
          - '**/*.yaml'
        url: ./ghaction

    - id: fetch-actions
      name: Fetch Helm Chart
      action: fetch:template
      input:
        url: ./helm
        values:
          repo: ${{ parameters.repoUrl | parseRepoUrl }}


    # This step publishes the contents of the working directory to GitHub.
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        defaultBranch: 'main'
        repoUrl: ${{ parameters.repoUrl }}

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
